spring:
  application:
    name: technical-test-api
  #  main:
  #    web-application-type: servlet
  data:
    mongodb:
      host: localhost
      port: 27017
      database: auchan-tech-test

server:
  port: 8086